---

# Automating MySQL Installation
- hosts: dbservers
  gather_facts: yes
  become: yes
  tasks:
    - name: Installing MySQL
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
        - mysql-server
        - mysql-common
        - python-mysqldb
    - name: Enabling Service
      service: name=mysql state=started enabled=yes
    - name: Set Password
      mysql_user:
        name: root
        password: tinnitus
    - name: Get Password
      src: my.cnf
      dest: /root/.my.cnf
      owner: root
      mode: 0600
